set(FREEGLUT_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
set(FREEGLUT_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/freeglut.lib")
set(FREEGLUT_DLL_PATH "${CMAKE_CURRENT_LIST_DIR}/lib/x86/freeglut.dll")
string(STRIP "${FREEGLUT_LIBRARIES}" FREEGLUT_LIBRARIES)