set(SPRITE_SHEET_FILES
    sprite_sheet/animation.h
    sprite_sheet/animation_parameters.h
    sprite_sheet/common.h
    sprite_sheet/sprite_sheet.h
    sprite_sheet/sprite_sheet_parameters.h
    sprite_sheet/sprite_sheet_serializer.h
	sprite_sheet/animation.cpp
	sprite_sheet/sprite_sheet.cpp
)