set(TILE_MAP_FILES
    tile_map/animated_tile.h
    tile_map/image_layer.h
    tile_map/layer.h
    tile_map/object_layer.h
    tile_map/tile_layer.h
    tile_map/tile_map.h
    tile_map/common.cpp
    tile_map/image_layer.cpp
    tile_map/object_layer.cpp
    tile_map/tile_layer.cpp
    tile_map/tile_map.cpp 
)