set(IMGUI_FILES
    im_gui/imconfig.h
    im_gui/imgui.h
    im_gui/imgui_internal.h
    im_gui/imstb_rectpack.h
    im_gui/imstb_textedit.h
    im_gui/imstb_truetype.h
    im_gui/backends/imgui_impl_opengl2.h
    im_gui/backends/imgui_impl_opengl3.h
    im_gui/backends/imgui_impl_osx.h
    im_gui/backends/imgui_impl_sdl2.h
    im_gui/backends/imgui_impl_sdlrenderer.h
    im_gui/backends/imgui_impl_win32.h
    im_gui/misc/cpp/imgui_stdlib.h
    im_gui/imgui.cpp
    im_gui/imgui_demo.cpp
    im_gui/imgui_draw.cpp
    im_gui/imgui_tables.cpp
    im_gui/imgui_widgets.cpp
    im_gui/backends/imgui_impl_opengl2.cpp
    im_gui/backends/imgui_impl_opengl3.cpp
    im_gui/backends/imgui_impl_sdl2.cpp
    im_gui/backends/imgui_impl_sdlrenderer.cpp
    im_gui/misc/cpp/imgui_stdlib.cpp
    im_gui/misc/fonts/binary_to_compressed_c.cpp
)